#pragma once
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <vector>
#include "stb_image.h"
#include "AtomColors.h"
#include <fstream>
#include <iostream>
#include <sstream>
#include <cmath>